version: '3.1'
services:
  thegame:
    image: 'gcr.io/balmy-script-278222/thegame:1.11'
    env_file:
      - 'thegame.env'
    ports:
      - '9000:9000'
  goraid:
    image: 'gcr.io/balmy-script-278222/goraid:0.3'
    env_file:
      - 'goraid.env'
    ports:
      - '9000:9000'
  frontend:
    depends_on:
      - 'thegame'
      - 'goraid'
    image: 'gcr.io/balmy-script-278222/games-nginx:0.17'
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - '/etc/letsencrypt:/etc/letsencrypt'
      - '/home/theilig/react/thegame:/usr/share/nginx/html/thegame'
      - '/home/theilig/react/goraid:/usr/share/nginx/html/goraid'
